### ISSUE TITLE
unklarer connected zustand

### ISSUE THREAD

**Issue by Farmer-cb** [h3llh0und/ioBroker.magentatv#5]
Servus
ich probiere es auch gerade, bekomme es aber leider nicht hin.
Adapter Installation hat soweit geklappt, das Einstellungsfenster kommt auch.
Hier trage ich unter
MagentaTv Receiver IP Adresse die IP meines Receivers ein Ports lasse ich vor eingestellt
unter lokale IP Adresse kommt automatisch nach speichern/schließen die IP des iobrokers

danach ChromeBrowser öffnen F12 für Entwickler-Fenster, hier den unter Filter DTA eintragen.
jetzt deinen Telekom-Link öffnen und einloggen.
jetzt finde ich im Entwicklerfenster die userID in "", die ID kopiere ich ohne "" und füge Sie in deinen MD5Hash link ein, rechts erhalte ich dann den MD5Hash, den kopiere ich mir und mache aus allen kleinen Buchstaben große Buchstaben, diese neue ID kopiere ich in den Adapter und speichern schließen.

im log steht
`

-- | -- | -- | --
magentatv.0 | 2022-01-14 16:32:45.416 | debug | Receiver connected
magentatv.0 | 2022-01-14 16:32:45.416 | debug | Received Message: <?xml version="1.0"?> <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"> <e:property> <messageBody>X-pairingCheck:AD6E2C64</messageBody> </e:property> <e:property> <uniqueDeviceID>31752549-2cc6-4011-a0e5-72b837032657</uniqueDeviceID> </e:property> </e:propertyset>
magentatv.0 | 2022-01-14 16:32:45.387 | debug | Callback Server started
magentatv.0 | 2022-01-14 16:32:45.370 | info | starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.magentatv, node: v14.18.1, js-controller: 3.3.21
magentatv.0 | 2022-01-14 16:32:41.429 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
magentatv.0 | 2022-01-14 16:32:41.428 | info | terminating
magentatv.0 | 2022-01-14 16:32:41.425 | info | Got terminate signal TERMINATE_YOURSELF

`

in den Objekten steht aber connected false

und jetzt stehe ich auf dem schlauch

**Comment by h3llh0und** [comment]
Den State hatte ich vergessen nach dem Verbinden zu setzen, stand noch auf der ToDo Liste. Jetzt ist es erledigt.
Nachdem im Log "Receiver connected" steht sollte die Verbindung aufgebaut sein und du kannst über die Objekte die einzelnen Tastenbefehle senden.

**Comment by Farmer-cb** [comment]
jetzt steht connected auf true, aber
Sollte hier dann nicht irgenwelche Daten im Datenpunkt stehen
![image](https://user-images.githubusercontent.com/38419234/149898082-6e17ecec-1e81-4335-83cf-a444c54961c7.png)

**Comment by h3llh0und** [comment]
Eigentlich sollten da Buttons zum drücken sein
![image](https://user-images.githubusercontent.com/6917818/149986363-fe7d10a5-d33c-462e-b491-6811d04a12aa.png)

Die Datenpunkte werden nur gefüllt wenn du den Receiver über den Adapter steuerst. Das Teil ist leider nicht sehr kommunikativ. Man bekommt nur Updates wenn man auch für den Befehl verantwortlich ist. Vllt kann ich da irgendwas machen das ich regelmäßig Updates bekomme. Doku mäßig gibts da leider nicht viel, ist viel Try and Error :(

**Comment by Farmer-cb** [comment]
ah,ja, jetzt kommt was, 

trotzdem voll cool

**Comment by h3llh0und** [comment]
:) Freut mich wenn es schon mal funzt.

Ich versuch das ganze noch etwas zu verbessern.
